version: '3'

services:
  numberword.api:
    image: numberwordapi:v1
    build:
      context: .
      dockerfile: NumberWord.Api/Dockerfile.dev
    ports:
      - "4300:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development