FROM microsoft/aspnetcore:2.0.5 AS base
WORKDIR /app
EXPOSE 80

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    unzip \
  && rm -rf /var/lib/apt/lists/* \
  && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg


FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /src
COPY NumberWord.sln ./
COPY NumberWord.Api/NumberWord.Api.csproj NumberWord.Api/
RUN dotnet restore -nowarn:msb3202,nu1503
COPY . .

WORKDIR /src/NumberWord.Api
RUN dotnet build -c Debug -o /app


FROM build AS publish
RUN dotnet publish -c Debug -o /app

FROM base AS final
WORKDIR /src
COPY --from=build /src .

WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["tail", "-f", "/dev/null"]

