version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.8.0-browsers
    steps:
      - checkout
      
      - setup_remote_docker:   
          docker_layer_caching: true 

      # build and push Docker image
      - run:
          name: Build docker image
          command: |
            TAG=api-0.$CIRCLE_BUILD_NUM
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker-compose -f docker-compose.yml build 
              docker tag numberwordapi:v1 baron123.azurecr.io/number-word/numberwordapi:$TAG
              docker login baron123.azurecr.io -u $DOCKER_USER -p $DOCKER_PASS        
              docker push baron123.azurecr.io/number-word/numberwordapi
            fi