version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.8.0-browsers
    steps:
      - checkout
      - run:
          name: Install gcloud
          command: |
            export CLOUDSDK_CORE_DISABLE_PROMPTS=1
            curl https://sdk.cloud.google.com | bash
            export PATH=${HOME}/google-cloud-sdk/bin:$PATH
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project number-2-text
            gcloud config set compute/zone australia-southeast1-a
      - setup_remote_docker:   
          docker_layer_caching: true 

      # build and push Docker image
      - run:
          name: Build docker image
          command: |
            TAG=api-0.$CIRCLE_BUILD_NUM
            export PATH=${HOME}/google-cloud-sdk/bin:$PATH
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              gcloud auth --quiet configure-docker
              docker-compose -f docker-compose.yml build 
              docker tag numberwordapi:v1 asia.gcr.io/number-2-text/numberwordapi:$TAG
              docker push asia.gcr.io/number-text-convert/numberwordapi
            fi
